version: '3.8'

services:
  # PostgreSQL Database
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  
    networks:
      - app-network


  # Ingestion Service
  ingestion:
    build: ./ingestion
    depends_on:
      - db
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: db
    networks:
      - app-network

  # Backend Service
  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: db
    ports:
      - '5001:3000' # Host port 5000 mapped to container port 3000
    networks:
      - app-network

  # Frontend Service
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - '3000:3000' # Expose frontend on port 3000
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
